dubbo:
  scan:
    base-packages: org.springframework.cloud.alibaba.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
  application:
    qos:
      enable: true
      port: 22223
      accept:
        foreign:
          ip: false


feign:
  hystrix:
    enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata